### ISSUE TITLE
Interesting code

### ISSUE THREAD

**Issue by smalltavern** [birdortyedi/neural-preset-pytorch#1]
Hello, I am very interested in your code and would like to ask if this is the code for the Neural Preset for Color Style Transfer in CVPR 2023. May I ask if you can provide your weight file

**Comment by birdortyedi** [comment]
Yes, but it's an unofficial implementation. 

We are not planning to share the weight files in our training. However, you may easily get your LUTs online, and integrate them into the code to train yourself. It does not take too much time even in limited computational resources.
