### ISSUE TITLE
Can you tell me about your reproduction results, such as whether there is any loss of contrast, and whether the results match those of the iOS app?

### ISSUE THREAD

**Issue by JingzhuT** [birdortyedi/neural-preset-pytorch#4]
Please...

**Comment by sangenan** [comment]
No, the model code provided by the author cannot perfectly reproduce the results of the paper.

**Comment by birdortyedi** [comment]
No, the results presented in the paper do not match the results since we do not use the same LUTs pool. LUTs used in the paper are private, and ours are commercially-licensed, so we could not share them.
