### ISSUE TITLE
Can you provide the download address of the LUTs?

### ISSUE THREAD

**Issue by zrk2002** [birdortyedi/neural-preset-pytorch#6]

**Comment by birdortyedi** [comment]
No, I can't because it's commercially licensed. 

You can find any custom LUT pack from websites selling design solutions for downloading for free or for 3-5$.

**Comment by zrk2002** [comment]
Could you please advise on what to consider when selecting LUTs? I've initially chosen a few thousand LUTs, but I'm unable to achieve the effect in the paper

**Comment by sangenan** [comment]
@zrk2002 @birdortyedi  Have you made any progress? I haven't gotten good results either; there's a serious color bias issue in the training outcomes.
